// analyst-reports.js — Scheduled email reports (DM daily brief, exec weekly report)
const https = require('https');
const { buildDataContext, buildKPISnapshot, STORES, getStoresByDistrict } = require('./analyst-data');
const { generateStructured } = require('./analyst-claude');
const { PERSONA } = require('./analyst-prompts');
const { cacheSave, cacheLoad } = require('./analyst-cache');
const { logAudit } = require('./analyst-audit');

// ── DM district mapping ─────────────────────────────────────────────────────
const DM_EMAILS = {
  1: { name: 'District 1 DM', email: null },
  2: { name: 'District 2 DM', email: null },
  3: { name: 'District 3 DM', email: null },
  4: { name: 'District 4 DM', email: null },
  5: { name: 'District 5 DM', email: null },
  6: { name: 'District 6 DM', email: null },
  7: { name: 'District 7 DM', email: null },
  8: { name: 'District 8 DM', email: null },
};

// ── Email sender ─────────────────────────────────────────────────────────────
function sendEmail({ to, cc, subject, html }) {
  const RESEND_KEY = process.env.RESEND_API_KEY;
  if (!RESEND_KEY) { console.warn('RESEND_API_KEY not set, skipping email'); return Promise.resolve(); }
  const FROM = process.env.NOTIFY_FROM || 'Orion — PCG Analyst <noreply@pcgops.com>';

  const payload = {
    from: FROM,
    to: Array.isArray(to) ? to : [to],
    subject,
    html,
  };
  if (cc && cc.length > 0) payload.cc = Array.isArray(cc) ? cc : [cc];

  const body = JSON.stringify(payload);
  return new Promise((resolve) => {
    const req = https.request({
      hostname: 'api.resend.com', port: 443, path: '/emails', method: 'POST',
      headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${RESEND_KEY}`, 'Content-Length': Buffer.byteLength(body) },
    }, (res) => {
      let raw = '';
      res.on('data', d => raw += d);
      res.on('end', () => { console.log('[analyst-reports] email sent:', raw); resolve(raw); });
    });
    req.on('error', (e) => { console.error('[analyst-reports] email error:', e.message); resolve(); });
    req.write(body);
    req.end();
  });
}

// ── Load report settings from blobs ──────────────────────────────────────────
async function loadReportSettings() {
  const settings = await cacheLoad('analyst/report-settings');
  return settings || {
    execReportCC: ['Mike@PeopleCapitalGroup.com'],
    dmBriefCC: ['Mike@PeopleCapitalGroup.com'],
    execReportEnabled: true,
    dmBriefEnabled: true,
  };
}

// ── Email template wrapper ───────────────────────────────────────────────────
function wrapEmail(title, subtitle, bodyHtml, footerNote) {
  return `
    <div style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 680px; margin: 0 auto; background: #ffffff;">
      <div style="background: linear-gradient(135deg, #0b0b0c 0%, #1a1a2e 100%); padding: 28px 32px; border-radius: 8px 8px 0 0;">
        <div style="display: flex; align-items: center; gap: 14px;">
          <div style="width: 44px; height: 44px; background: #FF671F22; border-radius: 12px; display: flex; align-items: center; justify-content: center; font-size: 24px;">🔮</div>
          <div>
            <h1 style="color: #fff; margin: 0; font-size: 20px; font-weight: 700;">${title}</h1>
            <p style="color: #FF671F; margin: 4px 0 0; font-size: 13px; font-weight: 600; letter-spacing: 0.5px;">${subtitle}</p>
          </div>
        </div>
      </div>
      <div style="padding: 28px 32px; border: 1px solid #e5e5e5; border-top: 3px solid #FF671F; border-radius: 0 0 8px 8px;">
        ${bodyHtml}
        ${footerNote ? `<div style="margin-top: 24px; padding: 14px 18px; background: #fff8f0; border-left: 3px solid #FF671F; border-radius: 0 6px 6px 0; font-size: 12px; color: #8b6914; line-height: 1.5;">${footerNote}</div>` : ''}
        <hr style="border: none; border-top: 1px solid #eee; margin: 24px 0;" />
        <p style="color: #999; font-size: 11px; text-align: center;">
          Generated by Orion — PCG Unified Operations Portal<br/>
          People Capital Group &bull; Confidential — Internal Use Only
        </p>
      </div>
    </div>
  `;
}

// ── Generate DM Daily Brief Email ────────────────────────────────────────────
async function generateDMBrief(district) {
  const today = new Date().toISOString().slice(0, 10);
  const dataContext = await buildDataContext({ district });
  if (typeof dataContext === 'string' && dataContext.includes('No labor data')) return null;

  const prompt = `Generate a morning briefing email for a District Manager (District ${district}) on ${today}.

Include:
1. A one-line greeting ("Good morning, here's your District ${district} brief for ${today}")
2. 3-5 key bullets: what happened yesterday, what to watch today
3. A "Store Spotlight" — highlight the best and worst performing store in the district
4. Any overtime or labor alerts
5. One actionable recommendation

Format as clean HTML suitable for email. Use <strong> for emphasis, <ul>/<li> for lists. Keep it under 250 words. Do not use markdown — use HTML tags only.

Data:
${dataContext}`;

  const result = await generateStructured({
    system: PERSONA,
    userPrompt: prompt,
    action: 'brief',
    userId: 'system',
  });

  return result.text;
}

// ── Generate Exec Weekly Report Email ────────────────────────────────────────
async function generateExecReport(isLaborAdjusted) {
  const today = new Date().toISOString().slice(0, 10);
  const dataContext = await buildDataContext({ includeStoreDetail: true });

  const adjustmentNote = isLaborAdjusted
    ? 'This is the post-adjustment report (Tuesday). Labor data reflects DM corrections made by Monday 1 PM deadline.'
    : 'This is the preliminary report (Sunday). Note: Labor data may be inaccurate until DM adjustments are completed by Monday at 1:00 PM ET.';

  const prompt = `Generate a weekly executive report for the VP of Operations on ${today}.

${adjustmentNote}

Include these sections (format as clean HTML for email, use <h3> for section headers, <table> for data):

1. **Executive Summary** — 2-3 sentence overview of the week
2. **Network KPIs** — Table with: Total Sales, Labor %, Guests, Avg Check, OT Count, Stores Reporting
3. **District Scorecard** — Table ranked by performance: District, Sales, Labor %, Store Count
4. **Top 5 / Bottom 5** — Two lists: best and worst performing stores by labor %
5. **Business Cases** — Any open anomaly-driven cases requiring attention
6. **Outlook & Recommendations** — 2-3 bullet points for the coming week

Keep it professional and concise. Under 400 words. Use HTML tags only (no markdown).

Data:
${dataContext}`;

  const result = await generateStructured({
    system: PERSONA,
    userPrompt: prompt,
    action: 'deep',
    userId: 'system',
  });

  return result.text;
}

// ── Send DM Daily Briefs ─────────────────────────────────────────────────────
async function sendDMBriefs(settings, users) {
  const today = new Date().toISOString().slice(0, 10);
  let sent = 0;

  for (let d = 1; d <= 8; d++) {
    try {
      const briefHtml = await generateDMBrief(d);
      if (!briefHtml) continue;

      // Find DM email from users list or settings
      const dmUser = (users || []).find(u => u.userType === 'dm' && u.district === d && u.active);
      const dmEmail = dmUser?.email || DM_EMAILS[d]?.email;
      if (!dmEmail) { console.log(`[analyst-reports] No email for DM D${d}, skipping`); continue; }

      const cc = settings.dmBriefCC || [];
      const subject = `Orion Brief — District ${d} — ${today}`;
      const html = wrapEmail(
        `District ${d} Morning Brief`,
        `ORION ANALYST • ${today}`,
        briefHtml,
        null
      );

      await sendEmail({ to: dmEmail, cc, subject, html });
      sent++;
      console.log(`[analyst-reports] Sent DM brief for D${d} to ${dmEmail}`);
    } catch (err) {
      console.warn(`[analyst-reports] Failed DM brief D${d}:`, err.message);
    }
  }

  return sent;
}

// ── Send Exec Weekly Report ──────────────────────────────────────────────────
async function sendExecReport(settings, isLaborAdjusted) {
  const today = new Date().toISOString().slice(0, 10);

  try {
    const reportHtml = await generateExecReport(isLaborAdjusted);
    if (!reportHtml) return false;

    const to = settings.execReportCC || ['Mike@PeopleCapitalGroup.com'];
    const reportType = isLaborAdjusted ? 'Post-Adjustment' : 'Preliminary';
    const subject = `Orion Exec Report — ${reportType} — Week of ${today}`;

    const laborCaveat = !isLaborAdjusted
      ? '<strong>⚠️ Labor Data Notice:</strong> This report contains preliminary labor figures. District Managers are required to complete all labor adjustments by <strong>Monday at 1:00 PM ET</strong>. A final post-adjustment report will be sent on Tuesday at 10:00 AM ET with corrected figures.'
      : '<strong>✅ Post-Adjustment Report:</strong> This report reflects labor data after DM corrections. Figures should be final.';

    const html = wrapEmail(
      `Weekly Executive Report — ${reportType}`,
      `ORION ANALYST • PEOPLE CAPITAL GROUP • ${today}`,
      reportHtml,
      laborCaveat
    );

    await sendEmail({ to, subject, html });
    console.log(`[analyst-reports] Sent exec report (${reportType}) to ${to.join(', ')}`);
    return true;
  } catch (err) {
    console.warn(`[analyst-reports] Failed exec report:`, err.message);
    return false;
  }
}

module.exports = { sendDMBriefs, sendExecReport, loadReportSettings, sendEmail, wrapEmail };
