// analyst-reports.js — Scheduled email reports (DM daily brief, exec weekly report)
const https = require('https');
const { buildDataContext, buildKPISnapshot, STORES, getStoresByDistrict } = require('./analyst-data');
const { generateStructured } = require('./analyst-claude');
const { PERSONA } = require('./analyst-prompts');
const { cacheSave, cacheLoad } = require('./analyst-cache');
const { logAudit } = require('./analyst-audit');

// ── DM district mapping ─────────────────────────────────────────────────────
const DM_EMAILS = {
  1: { name: 'District 1 DM', email: null },
  2: { name: 'District 2 DM', email: null },
  3: { name: 'District 3 DM', email: null },
  4: { name: 'District 4 DM', email: null },
  5: { name: 'District 5 DM', email: null },
  6: { name: 'District 6 DM', email: null },
  7: { name: 'District 7 DM', email: null },
  8: { name: 'District 8 DM', email: null },
};

// ── Email sender ─────────────────────────────────────────────────────────────
function sendEmail({ to, cc, subject, html }) {
  const RESEND_KEY = process.env.RESEND_API_KEY;
  if (!RESEND_KEY) { console.warn('RESEND_API_KEY not set, skipping email'); return Promise.resolve(); }
  const FROM = process.env.NOTIFY_FROM || 'Orion — PCG Analyst <noreply@pcgops.com>';

  const payload = {
    from: FROM,
    to: Array.isArray(to) ? to : [to],
    subject,
    html,
  };
  if (cc && cc.length > 0) payload.cc = Array.isArray(cc) ? cc : [cc];

  const body = JSON.stringify(payload);
  return new Promise((resolve) => {
    const req = https.request({
      hostname: 'api.resend.com', port: 443, path: '/emails', method: 'POST',
      headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${RESEND_KEY}`, 'Content-Length': Buffer.byteLength(body) },
    }, (res) => {
      let raw = '';
      res.on('data', d => raw += d);
      res.on('end', () => { console.log('[analyst-reports] email sent:', raw); resolve(raw); });
    });
    req.on('error', (e) => { console.error('[analyst-reports] email error:', e.message); resolve(); });
    req.write(body);
    req.end();
  });
}

// ── Load report settings from blobs ──────────────────────────────────────────
async function loadReportSettings() {
  const settings = await cacheLoad('analyst/report-settings');
  return settings || {
    execReportCC: ['Mike@PeopleCapitalGroup.com'],
    dmBriefCC: ['Mike@PeopleCapitalGroup.com'],
    execReportEnabled: true,
    dmBriefEnabled: true,
  };
}

// ── Email template wrapper ───────────────────────────────────────────────────
function wrapEmail(title, subtitle, bodyHtml, footerNote) {
  return `
    <div style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 680px; margin: 0 auto; background: #ffffff;">
      <div style="background: linear-gradient(135deg, #0b0b0c 0%, #1a1a2e 100%); padding: 28px 32px; border-radius: 8px 8px 0 0;">
        <div style="display: flex; align-items: center; gap: 14px;">
          <div style="width: 44px; height: 44px; background: rgba(255,103,31,0.15); border-radius: 12px; display: flex; align-items: center; justify-content: center; font-size: 24px; line-height: 1;">&#128302;</div>
          <div>
            <h1 style="color: #fff; margin: 0; font-size: 20px; font-weight: 700;">${title}</h1>
            <p style="color: #FF671F; margin: 4px 0 0; font-size: 13px; font-weight: 600; letter-spacing: 0.5px;">${subtitle}</p>
          </div>
        </div>
      </div>
      <div style="padding: 28px 32px; border: 1px solid #e5e5e5; border-top: 3px solid #FF671F; border-radius: 0 0 8px 8px;">
        ${bodyHtml}
        ${footerNote ? `<div style="margin-top: 24px; padding: 14px 18px; background: #fff8f0; border-left: 3px solid #FF671F; border-radius: 0 6px 6px 0; font-size: 12px; color: #8b6914; line-height: 1.5;">${footerNote}</div>` : ''}
        <hr style="border: none; border-top: 1px solid #eee; margin: 24px 0;" />
        <p style="color: #999; font-size: 11px; text-align: center;">
          Generated by Orion — PCG Unified Operations Portal<br/>
          People Capital Group &bull; Confidential — Internal Use Only
        </p>
      </div>
    </div>
  `;
}

// ── Generate DM Daily Brief Email ────────────────────────────────────────────
async function generateDMBrief(district) {
  const today = new Date().toISOString().slice(0, 10);
  const dataContext = await buildDataContext({ district });
  if (typeof dataContext === 'string' && dataContext.includes('No labor data')) return null;

  const prompt = `Generate a morning briefing email for a District Manager (District ${district}) on ${today}.

Include:
1. A one-line greeting ("Good morning, here's your District ${district} brief for ${today}")
2. 3-5 key bullets: what happened yesterday, what to watch today
3. A "Store Spotlight" — highlight the best and worst performing store in the district
4. Any overtime or labor alerts
5. One actionable recommendation

Format as clean HTML suitable for email. Use <strong> for emphasis, <ul>/<li> for lists. Keep it under 250 words. Do not use markdown — use HTML tags only.

Data:
${dataContext}`;

  const result = await generateStructured({
    system: PERSONA,
    userPrompt: prompt,
    action: 'brief',
    userId: 'system',
  });

  return result.text;
}

// ── Generate Exec Weekly Report Email ────────────────────────────────────────
async function generateExecReport(isLaborAdjusted) {
  const today = new Date().toISOString().slice(0, 10);
  const snapshot = await buildKPISnapshot();
  if (snapshot.error) return null;

  const net = snapshot.network;
  const stores = snapshot.stores || [];
  const fmtD = v => '$' + Math.round(v).toLocaleString();
  const fmtP = v => (v || 0).toFixed(1) + '%';

  // Build district summaries from WTD data
  const distMap = {};
  for (const s of stores) {
    const d = s.district || 0;
    if (!distMap[d]) distMap[d] = { sales: 0, labor: 0, stores: 0, ot: 0 };
    distMap[d].sales += s.wtd?.sales || 0;
    distMap[d].labor += s.wtd?.laborDollars || 0;
    distMap[d].stores++;
    distMap[d].ot += s.today?.overtimeCount || 0;
  }

  // Sort stores by WTD labor % for top/bottom
  const storesWithWtd = stores.filter(s => s.wtd?.sales > 0).map(s => ({
    ...s, wtdLaborPct: s.wtd.sales > 0 ? (s.wtd.laborDollars / s.wtd.sales) * 100 : 0
  }));
  storesWithWtd.sort((a, b) => a.wtdLaborPct - b.wtdLaborPct);
  const best5 = storesWithWtd.slice(0, 5);
  const worst5 = storesWithWtd.slice(-5).reverse();

  // Network WTD totals
  const wtdSales = stores.reduce((s, st) => s + (st.wtd?.sales || 0), 0);
  const wtdLabor = stores.reduce((s, st) => s + (st.wtd?.laborDollars || 0), 0);
  const wtdLaborPct = wtdSales > 0 ? (wtdLabor / wtdSales) * 100 : 0;

  const tblStyle = 'width:100%;border-collapse:collapse;font-size:14px;margin:12px 0 20px;';
  const thStyle = 'padding:10px 12px;text-align:left;border-bottom:2px solid #FF671F;font-weight:700;font-size:12px;text-transform:uppercase;letter-spacing:0.5px;color:#666;';
  const tdStyle = 'padding:8px 12px;border-bottom:1px solid #eee;';
  const tdBold = 'padding:8px 12px;border-bottom:1px solid #eee;font-weight:700;';

  // Build the HTML directly — no LLM formatting needed for the data tables
  let html = '';

  // Get LLM to write ONLY the executive summary (2-3 sentences) — much more reliable
  const dataContext = await buildDataContext({ includeStoreDetail: false });
  const summaryPrompt = `Write a 2-3 sentence executive summary for a weekly operations report. Data as of ${today}. WTD Network Sales: ${fmtD(wtdSales)}, WTD Labor: ${fmtP(wtdLaborPct)}, ${net.storeCount} stores, ${net.overtimeCount} OT employees. ${isLaborAdjusted ? 'This is the post-adjustment report — labor figures are final.' : 'This is the preliminary report — labor figures may change after DM adjustments.'} Be concise and professional. Return plain text only, no HTML tags, no markdown.`;

  let summaryText = '';
  try {
    const summaryResult = await generateStructured({ system: PERSONA, userPrompt: summaryPrompt, action: 'brief', userId: 'system' });
    summaryText = summaryResult.text.replace(/<[^>]+>/g, '').replace(/```/g, '').replace(/\*\*/g, '').trim();
  } catch { summaryText = `The network recorded ${fmtD(wtdSales)} in WTD sales across ${net.storeCount} stores with a ${fmtP(wtdLaborPct)} labor rate.`; }

  html += `<h3 style="color:#0b0b0c;font-size:16px;margin:0 0 8px;">Executive Summary</h3>`;
  html += `<p style="font-size:14px;line-height:1.6;color:#333;margin:0 0 20px;">${summaryText}</p>`;

  // Network KPIs
  html += `<h3 style="color:#0b0b0c;font-size:16px;margin:0 0 8px;">Network KPIs — Week to Date</h3>`;
  html += `<table style="${tblStyle}">`;
  html += `<tr><th style="${thStyle}">Metric</th><th style="${thStyle}">Value</th></tr>`;
  html += `<tr><td style="${tdStyle}">WTD Net Sales</td><td style="${tdBold}color:#00d084;">${fmtD(wtdSales)}</td></tr>`;
  html += `<tr><td style="${tdStyle}">WTD Labor Cost</td><td style="${tdBold}">${fmtD(wtdLabor)}</td></tr>`;
  html += `<tr><td style="${tdStyle}">WTD Labor %</td><td style="${tdBold}color:${wtdLaborPct > 26 ? '#f44336' : wtdLaborPct > 23 ? '#ff9800' : '#4caf50'};">${fmtP(wtdLaborPct)}</td></tr>`;
  html += `<tr><td style="${tdStyle}">Stores Reporting</td><td style="${tdBold}">${net.storeCount}</td></tr>`;
  html += `<tr><td style="${tdStyle}">Employees in OT</td><td style="${tdBold}color:${net.overtimeCount > 10 ? '#f44336' : '#333'};">${net.overtimeCount}</td></tr>`;
  html += `<tr><td style="${tdStyle}">Scheduled Now</td><td style="${tdBold}">${net.scheduledNow}</td></tr>`;
  html += `</table>`;

  // District Scorecard
  html += `<h3 style="color:#0b0b0c;font-size:16px;margin:0 0 8px;">District Scorecard</h3>`;
  html += `<table style="${tblStyle}">`;
  html += `<tr><th style="${thStyle}">District</th><th style="${thStyle}">WTD Sales</th><th style="${thStyle}">WTD Labor %</th><th style="${thStyle}">Stores</th><th style="${thStyle}">OT</th></tr>`;
  const distEntries = Object.entries(distMap).sort((a, b) => {
    const aPct = a[1].sales > 0 ? (a[1].labor / a[1].sales) * 100 : 0;
    const bPct = b[1].sales > 0 ? (b[1].labor / b[1].sales) * 100 : 0;
    return aPct - bPct;
  });
  for (const [d, v] of distEntries) {
    const pct = v.sales > 0 ? (v.labor / v.sales) * 100 : 0;
    const pctColor = pct > 26 ? '#f44336' : pct > 23 ? '#ff9800' : '#4caf50';
    html += `<tr><td style="${tdBold}">D${d}</td><td style="${tdStyle}">${fmtD(v.sales)}</td><td style="${tdStyle}color:${pctColor};font-weight:700;">${fmtP(pct)}</td><td style="${tdStyle}">${v.stores}</td><td style="${tdStyle}">${v.ot}</td></tr>`;
  }
  html += `</table>`;

  // Top 5 / Bottom 5
  html += `<div style="display:flex;gap:24px;flex-wrap:wrap;margin-bottom:20px;">`;
  html += `<div style="flex:1;min-width:200px;"><h3 style="color:#4caf50;font-size:14px;margin:0 0 8px;">Top 5 — Best Labor %</h3>`;
  for (const s of best5) {
    html += `<div style="padding:4px 0;font-size:13px;border-bottom:1px solid #f0f0f0;"><strong>${s.name}</strong> (D${s.district}) — <span style="color:#4caf50;font-weight:700;">${fmtP(s.wtdLaborPct)}</span> · ${fmtD(s.wtd.sales)}</div>`;
  }
  html += `</div>`;
  html += `<div style="flex:1;min-width:200px;"><h3 style="color:#f44336;font-size:14px;margin:0 0 8px;">Bottom 5 — Highest Labor %</h3>`;
  for (const s of worst5) {
    html += `<div style="padding:4px 0;font-size:13px;border-bottom:1px solid #f0f0f0;"><strong>${s.name}</strong> (D${s.district}) — <span style="color:#f44336;font-weight:700;">${fmtP(s.wtdLaborPct)}</span> · ${fmtD(s.wtd.sales)}</div>`;
  }
  html += `</div></div>`;

  return html;
}

// ── Send DM Daily Briefs ─────────────────────────────────────────────────────
async function sendDMBriefs(settings, users) {
  const today = new Date().toISOString().slice(0, 10);
  let sent = 0;

  for (let d = 1; d <= 8; d++) {
    try {
      const briefHtml = await generateDMBrief(d);
      if (!briefHtml) continue;

      // Find DM email from users list — skip if excluded
      const dmUser = (users || []).find(u => u.userType === 'dm' && u.district === d && u.active);
      const excludedDM = settings.excludeDM || [];
      if (dmUser && excludedDM.includes(dmUser.id)) { console.log(`[analyst-reports] DM D${d} excluded, skipping`); continue; }
      const dmEmail = dmUser?.email || DM_EMAILS[d]?.email;
      if (!dmEmail) { console.log(`[analyst-reports] No email for DM D${d}, skipping`); continue; }

      const cc = settings.dmBriefCC || [];
      const subject = `Orion Brief — District ${d} — ${today}`;
      const html = wrapEmail(
        `District ${d} Morning Brief`,
        `ORION ANALYST • ${today}`,
        briefHtml,
        null
      );

      await sendEmail({ to: dmEmail, cc, subject, html });
      sent++;
      console.log(`[analyst-reports] Sent DM brief for D${d} to ${dmEmail}`);
    } catch (err) {
      console.warn(`[analyst-reports] Failed DM brief D${d}:`, err.message);
    }
  }

  return sent;
}

// ── Send Exec Weekly Report ──────────────────────────────────────────────────
async function sendExecReport(settings, isLaborAdjusted) {
  const today = new Date().toISOString().slice(0, 10);

  try {
    const reportHtml = await generateExecReport(isLaborAdjusted);
    if (!reportHtml) return false;

    // Build recipient list: CC list minus excluded users
    const excludedExec = settings.excludeExec || [];
    const to = (settings.execReportCC || ['Mike@PeopleCapitalGroup.com']).filter(email => {
      // CC emails aren't user IDs so they're never excluded — exclusion only applies to auto-detected users
      return true;
    });
    if (to.length === 0) { console.log('[analyst-reports] No exec report recipients, skipping'); return false; }
    const reportType = isLaborAdjusted ? 'Post-Adjustment' : 'Preliminary';
    const subject = `Orion Exec Report — ${reportType} — Week of ${today}`;

    const laborCaveat = !isLaborAdjusted
      ? '<strong>⚠️ Labor Data Notice:</strong> This report contains preliminary labor figures. District Managers are required to complete all labor adjustments by <strong>Monday at 1:00 PM ET</strong>. A final post-adjustment report will be sent on Tuesday at 10:00 AM ET with corrected figures.'
      : '<strong>✅ Post-Adjustment Report:</strong> This report reflects labor data after DM corrections. Figures should be final.';

    const html = wrapEmail(
      `Weekly Executive Report — ${reportType}`,
      `ORION ANALYST • PEOPLE CAPITAL GROUP • ${today}`,
      reportHtml,
      laborCaveat
    );

    await sendEmail({ to, subject, html });
    console.log(`[analyst-reports] Sent exec report (${reportType}) to ${to.join(', ')}`);
    return true;
  } catch (err) {
    console.warn(`[analyst-reports] Failed exec report:`, err.message);
    return false;
  }
}

module.exports = { sendDMBriefs, sendExecReport, loadReportSettings, sendEmail, wrapEmail };
